on:
  issues:
    types: [opened, labeled]

jobs:
  open_PR_message:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "Hello! :wave:\n\nThis issue is being automatically closed, Please open a issue or PR with a relevant fix."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/close-matching-issues@v2
        with:
          query: 'label:invalid'
          token: ${{ secrets.GITHUB_TOKEN }}
