#Thank you message after PR is merged

name: Thank you

on:
  pull_request:
    types: [merged]

jobs:
  thank_you:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for your contribution! Your pull request has been merged 🎉.
            We will be sure to credit you and we have added you to our contributors list.
            Keep Contributing to Hacktoberfest 2022!
            If you have any doubts or suggestions, please comment below. I will be happy to help you out.